### PR TITLE
WIP - fix bottom safe area, doesn't work

### PR DESCRIPTION
**Pull request by user512**
https://github.com/zinc-collective/mp-shake-it-photo/issues/35

I am trying to respect the safe area from the bottom because users cannot tap the plus icon sometimes, it's too close to the bottom.

SO reference:
https://stackoverflow.com/a/47076040

### CODE REVIEW

**Comment by theInternauts** [comment]
If this is meant to address issue #35 I have a fix for that in the 3.3.1 branch by adjusting the centering/alignment and moving the entire bar up a few dozen pixels.  (I'm going to rename that branch to 3.5.0 tonight).

**Comment by theInternauts** [comment]
I was thinking of issue #26 I think they are the same issue.

**Comment by user512** [comment]
Thanks @theInternauts, will check it out.

**Comment by zspencer** [comment]
@user512 - should we close this?

**Comment by theInternauts** [comment]
out of date

**Pull request closed without merging**
