### PR TITLE
Firebase update

### PR DESCRIPTION
**Pull request by theInternauts**
The old Fabric-integrated Firebase SDK is deprecated.  I'm putting in the new and improved Firebase Crashlytics SDK at Google's behest.

### CODE REVIEW

**Comment by theInternauts** [comment]
Is iOS 14.x the right deployment target (from iOS 9.x)?   I think XCode Beta may have changed that for me while "helping."
Thoughts?

**Review by user512 — APPROVED** [review]
I don't have a lot of experience in iOS but I think it makes sense.

**Comment by zspencer** [comment]
I believe we want to pick a deployment target that is within the last 2~4 versions; as the deployment target sets the minimum iOS version that we will support. See: https://www.avanderlee.com/workflow/minimum-ios-version/

**Review by zspencer — APPROVED** [review]
Thanks! This looks great!

**Pull request merged**
